name    'jcalles-firefox'
version '0.1.0'
source '0.0.4'
author 'Javier Calles'
license 'Apache License, Version 2.0'
summary 'This module allows control of the profiles and global preferences firefox. Testing onFirefox 17 CentOS6.4'
description '-. Basically controls two files:
firefox.js file in /usr/lib64/firefox/defaults/preferences/ 
    or /usr/lib/firefox/defaults/pref/ 

firefox.cfg file in /usr/lib64/firefox/
    or  /usr/lib/firefox/

-. Depends:
CentOS/Redhat: EPEL repository or package firefox-17.0.8-1.el6.centos.x86_64.rpm
Ubuntu/Debian: sourcelist

-. One was developed for (CentOS/RedHat)6.4, however it can be exported to other platforms.'
project_page 'https://github.com/jcalles/puppet-firefox'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
